import {
  Bell,
  CheckCheck,
  CircleUserRound,
  FileSignature,
  Files,
  FolderGit2,
  FolderKanban,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  MessageSquareText,
  ShieldAlert,
  UsersRound,
} from 'lucide-react';

export const customerNavigation = [
  { to: '/dashboard', label: 'Обзор', icon: LayoutDashboard },
  { to: '/dashboard/contracts', label: 'Договоры', icon: FileSignature },
  { to: '/dashboard/finance', label: 'Финансы', icon: Landmark },
  { to: '/dashboard/risks', label: 'Риски', icon: ShieldAlert },
  { to: '/dashboard/issues', label: 'Замечания', icon: ShieldAlert },
  { to: '/dashboard/requests', label: 'Запросы', icon: FolderGit2 },
  { to: '/dashboard/projects', label: 'Проекты', icon: FolderKanban },
  { to: '/dashboard/documents', label: 'Документы', icon: Files },
  { to: '/dashboard/approvals', label: 'Согласования', icon: CheckCheck },
  { to: '/dashboard/conversations', label: 'Сообщения', icon: MessageSquareText },
  { to: '/dashboard/notifications', label: 'Уведомления', icon: Bell },
  { to: '/dashboard/team', label: 'Команда', icon: UsersRound },
  { to: '/dashboard/support', label: 'Поддержка', icon: LifeBuoy },
  { to: '/dashboard/profile', label: 'Профиль', icon: CircleUserRound },
];
